apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-1
  namespace: backend-prod
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: asia-south1-docker.pkg.dev/proud-storm-464205-p3/backend/helloworld:py-0.1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: backend-prod
spec:
  selector:
    app: helloworld
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer